<?php

namespace App\Models;

use App\Enums\BillState;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * 
 *
 * @property int $id
 * @property string $req_id [ReqId] Service Provider Unique Bill Request Identification number
 * @property string $sp_code [SpCode] Service Provider Code
 * @property string|null $bill_desc [BillDesc] Bill Description
 * @property string $cust_tin [CustTin] Customer Tax Identification Number (TIN)
 * @property string $cust_id [CustId] Customer Reference
 * @property string $cust_id_typ [CustIdTyp] Customer Identification Reference Type
 * @property string|null $cust_accnt [CustAccnt] Customer Account Number
 * @property string $cust_name [CustName] Customer Name
 * @property string|null $cust_cell_num [CustCellNum] Customer Mobile/Cell Number should have twelve digits including country code e.g. 255XXXXXXXXX
 * @property string|null $cust_email [CustEmail] Customer Email Address
 * @property string $expires_on
 * @property string|null $bill_gen_by [BillGenBy] Bill Generated By
 * @property string|null $bill_appr_by [BillApprBy] Bill Approved By
 * @property string $bill_amt [BillAmt] Billed Amount can be decimal with precision of two
 * @property string $bill_eqv_amt [BillEqvAmt] Equivalent Billed Amount should be equal to the summation of all item equivalent amounts. Always submitted as TZS.
 * @property string $ccy [Ccy] Currency Code - Billed Amount Currency must be standard currency code
 * @property string|null $bill_cntr_num [BillCntrNum] Bill Control Number
 * @property string|null $cust_cntr_num [CustCntrNum] Customer Control Number
 * @property string|null $bill_sts_code [BillStsCode] Bill Status Code
 * @property string|null $bill_sts_desc [BillStsDesc] Bill Status Description
 * @property string|null $cancl_reasn [CanclReasn] Bill Cancellation reason
 * @property string|null $cancl_gen_by [CanclGenBy] Individual initiated bill cancellation from SP system
 * @property string|null $cancl_appr_by [CanclApprBy] Individual initiated bill approved cancellation from SP system
 * @property string|null $cancl_sts [CanclSts] Bill Cancellation General Status: GF – GePG Failure, GS – GePG Success
 * @property string|null $cancl_sts_code [CanclStsCode] Bill Cancellation Status Code
 * @property string|null $cancl_sts_desc [CanclStsDesc] Bill Cancellation Status Description
 * @property BillState $state
 * @property string $external_callback_url
 * @property string|null $raw_gepg_response
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection<int, \App\Models\BillItem> $items
 * @property-read int|null $items_count
 * @method static \Illuminate\Database\Eloquent\Builder|Bill newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Bill newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Bill query()
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereBillAmt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereBillApprBy($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereBillCntrNum($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereBillDesc($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereBillEqvAmt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereBillGenBy($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereBillStsCode($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereBillStsDesc($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCanclApprBy($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCanclGenBy($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCanclReasn($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCanclSts($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCanclStsCode($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCanclStsDesc($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCcy($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCustAccnt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCustCellNum($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCustCntrNum($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCustEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCustId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCustIdTyp($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCustName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCustTin($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereExpiresOn($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereExternalCallbackUrl($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereRawGepgResponse($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereReqId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereSpCode($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereState($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Bill extends Model
{
    use HasFactory;

    protected function casts(): array
    {
        return [
            'state' => BillState::class,
        ];
    }

    protected $fillable = [
        'req_id',
        'sp_code',
        'bill_desc',
        'cust_tin',
        'cust_id',
        'cust_id_typ',
        'cust_accnt',
        'cust_name',
        'cust_cell_num',
        'cust_email',
        'expires_on',
        'bill_gen_by',
        'bill_appr_by',
        'bill_amt',
        'bill_eqv_amt',
        'ccy',
        'bill_cntr_num',
        'cust_cntr_num',
        'bill_sts_code',
        'bill_sts_desc',
        'cancl_reasn',
        'cancl_gen_by',
        'cancl_appr_by',
        'cancl_sts',
        'cancl_sts_code',
        'cancl_sts_desc',
        'state',
        'external_callback_url',
    ];

    public function items(): HasMany
    {
        return $this->hasMany(BillItem::class);
    }
}
