<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 *
 *
 * @property int $id
 * @property string $req_id [ReqId] Service Provider Unique Bill Request Identification number
 * @property string $sp_grp_code [SpGrpCode] Service Provider Group Code
 * @property string $sys_code [SysCode] Service Provider Identification Code
 * @property int $bill_typ [BillTyp] Type of the bill
 * @property int $pay_typ [PayTyp] Payment Type: 1 – Pay All Bill Control Numbers At Once, 2 – Pay any Bill Control Number
 * @property string $grp_bill_id [GrpBillId] Unique identification of the Bill in Service Provider Billing System
 * @property string $bill_id [BillId] Unique identification of the Bill in Service Provider Billing System
 * @property string $sp_code [SpCode] Service Provider Code
 * @property string|null $coll_cent_code [CollCentCode] Code identifying Service Provider Collection Centre
 * @property string|null $bill_desc [BillDesc] Bill Description
 * @property string $cust_tin [CustTin] Customer Tax Identification Number (TIN)
 * @property string $cust_id [CustId] Customer Reference
 * @property string $cust_id_typ [CustIdTyp] Customer Identification Reference Type
 * @property string $cust_accnt [CustAccnt] Customer Account Number
 * @property string $cust_name [CustName] Customer Name
 * @property string|null $cust_cell_num [CustCellNum] Customer Mobile/Cell Number should have twelve digits including country code e.g. 255XXXXXXXXX
 * @property string|null $cust_email [CustEmail] Customer Email Address
 * @property string $bill_gen_dt [BillGenDt] Bill Generation Date with format YYYY-MM-DDTHH24:MI:SS (Accepts today and past dates only)
 * @property string $bill_expr_dt [BillExprDt] Bill Expiry Date with format YYYY-MM-DDTHH24:MI:SS
 * @property string|null $bill_gen_by [BillGenBy] Bill Generated By
 * @property string|null $bill_appr_by [BillApprBy] Bill Approved By
 * @property string $bill_amt [BillAmt] Billed Amount can be decimal with precision of two
 * @property string $bill_eqv_amt [BillEqvAmt] Equivalent Billed Amount should be equal to the summation of all item equivalent amounts. Always submitted as TZS.
 * @property string $min_pay_amt [MinPayAmt] Minimum Bill Payable Amount - This field carries the minimum amount payable value of a specific bill. This field is most relevant in PARTIAL, LIMITED, and INFINITY bill pay options.
 * @property string $ccy [Ccy] Currency Code - Billed Amount Currency must be standard currency code
 * @property string $exch_rate [ExchRate] Billed Amount Currency Exchange Rate Value to Tanzanian Shillings
 * @property int $bill_pay_opt [BillPayOpt] Bill Payment Options define the rules with which the bill should be paid. Can have values: 1: FULL Bill (paid in one instalment), 2: PARTIAL Bill (multiple instalments), 3: EXACT Bill (paid exactly equal to billed amount), 4: INFINITY Payment Option (any amount greater than zero), 5: LIMITED Payment Option (single or multiple instalments)
 * @property int $pay_plan [PayPlan] Bill Payment Plan (Default: 1): 1: POST-PAID (bill issued after service assessment), 2: PRE-PAID (payment for service defined and submitted by customer)
 * @property int $pay_lim_typ [PayLimTyp] Bill Payment Limitation Type: 1: Normal Payment (No Limitation), 2: All Commercial Bank Payment Limitation, 3: Central Bank Limitation, 4: Central Bank and Specific Commercial Bank Limitation, 5: Specific Commercial Bank Limitation
 * @property string $pay_lim_amt [PayLimAmt] Payment Limitation Amount - This field carries the maximum limitation value for a transaction
 * @property string $coll_psp [CollPsp] Collection Payment Service Provider - This field carries a list of only PSP Codes allowed to settle a specific bill
 * @property string $bill_cntr_num [BillCntrNum] Bill Control Number
 * @property string|null $reuse_reasn [ReuseReasn] Reason for Bill Reuse
 * @property int $rtr_resp_flg [RtrRespFlg] Return Response Flag - Boolean if True then response for the submit request is required
 * @property int $rem_flag [RemFlag] Reminder Flag - True if reminder must be sent to the billed entity
 * @property string $cust_cntr_num [CustCntrNum] Customer Control Number
 * @property string $cancl_reasn [CanclReasn] Bill Cancellation reason
 * @property string $bill_sts_code [BillStsCode] Bill Status Code
 * @property string $bill_sts_desc [BillStsDesc] Bill Status Description
 * @property string $cancl_gen_by [CanclGenBy] Individual initiated bill cancellation from SP system
 * @property string $cancl_appr_by [CanclApprBy] Individual initiated bill approved cancellation from SP system
 * @property string $cancl_sts [CanclSts] Bill Cancellation General Status: GF – GePG Failure, GS – GePG Success
 * @property string $cancl_sts_code [CanclStsCode] Bill Cancellation Status Code
 * @property string $cancl_sts_desc [CanclStsDesc] Bill Cancellation Status Description
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|Bill newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Bill newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Bill query()
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereBillAmt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereBillApprBy($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereBillCntrNum($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereBillDesc($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereBillEqvAmt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereBillExprDt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereBillGenBy($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereBillGenDt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereBillId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereBillPayOpt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereBillStsCode($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereBillStsDesc($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereBillTyp($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCanclApprBy($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCanclGenBy($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCanclReasn($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCanclSts($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCanclStsCode($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCanclStsDesc($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCcy($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCollCentCode($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCollPsp($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCustAccnt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCustCellNum($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCustCntrNum($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCustEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCustId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCustIdTyp($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCustName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereCustTin($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereExchRate($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereGrpBillId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereMinPayAmt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill wherePayLimAmt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill wherePayLimTyp($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill wherePayPlan($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill wherePayTyp($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereRemFlag($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereReqId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereReuseReasn($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereRtrRespFlg($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereSpCode($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereSpGrpCode($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereSysCode($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Bill whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Bill extends Model
{
    use HasFactory;
}
