<?php

namespace App\Enums;

enum GEPGResponseCodes: string
{
    case SUCCESSFUL = '7101';
    case FAILURE = '7201';
    case REQUIRED_HEADER_NOT_GIVEN = '7202';
    case UNAUTHORIZED = '7203';
    case BILL_DOES_NOT_EXIST = '7204';
    case INVALID_SERVICE_PROVIDER = '7205';
    case SERVICE_PROVIDER_NOT_ACTIVE = '7206';
    case DUPLICATE_PAYMENT = '7207';
    case INVALID_BUSINESS_ACCOUNT = '7208';
    case BUSINESS_ACCOUNT_NOT_ACTIVE = '7209';
    case COLLECTION_ACCOUNT_BALANCE_LIMIT_REACHED = '7210';
    case PSP_CODE_MISMATCH = '7211';
    case PAYMENT_CURRENCY_MISMATCH_BILL_CURRENCY = '7212';
    case BILL_HAS_EXPIRED = '7213';
    case INSUFFICIENT_AMOUNT_PAID = '7214';
    case INVALID_PAYMENT_SERVICE_PROVIDER = '7215';
    case PAYMENT_SERVICE_PROVIDER_NOT_ACTIVE = '7216';
    case WRONG_CURRENCY = '7219';
    case INVALID_SESSION = '7241';
    case INVALID_REQUEST_DATA = '7242';
    case BILL_ALREADY_SETTLED = '7279';
    case INVALID_PAYMENT_TRANSACTION_DATE = '7281';
    case PAYMENT_CURRENCY_MISMATCH_COLLECTION_ACCOUNT_CURRENCY = '7284';
    case INVALID_BATCH_GENERATED_DATE = '7289';
    case TOTAL_BATCH_AMOUNT_CANNOT_BE_ZERO = '7290';
    case TOTAL_BATCH_AMOUNT_NOT_EQUAL_TO_SUM_OF_ITEMS = '7291';
    case INACTIVE_CURRENCY = '7297';
    case BILL_PAID_PARTIALLY = '7301';
    case PAID_AMOUNT_NOT_EXACT_BILLED_AMOUNT = '7302';
    case INVALID_SIGNATURE = '7303';
    case INVALID_SIGNATURE_CONFIGURATION = '7304';
    case INVALID_BATCH_START_AND_END_DATE = '7305';
    case BATCH_HAS_NO_ITEM = '7306';
    case INCONSISTENCY_BATCH_DATE = '7307';
    case INVALID_GEPG_CONFIGURATIONS = '7311';
    case ERROR_PROCESSING_REQUEST = '7317';
    case INVALID_RECONCILIATION_REQUEST_DATE = '7318';
    case RECONCILIATION_REQUEST_DATE_OUT_OF_RANGE = '7319';
    case REQUEST_CANNOT_COMPLETE_TRY_LATER = '7321';
    case INACTIVE_COMMUNICATION_PROTOCOL = '7322';
    case INVALID_CODE_MISMATCH_INFO_AND_HEADER = '7323';
    case INVALID_BILL_CONTROL_NUMBER = '7333';
    case REQUESTED_BILL_CONTROL_NUMBER_DOES_NOT_EXIST = '7335';
    case REQUESTED_BILL_AMOUNT_REACHED_MAX_PAYABLE_LIMIT = '7336';
    case REQUESTED_RESOURCE_NOT_AVAILABLE = '7337';
}
